pipeline {
    agent {
        label 'java-maven'
    }

    stages {
        stage('Integration Tests') {
            steps {
                sh '''
                    mvn test
                '''
            }
        }
    }
}