pipeline {
    agent {
        label 'java-maven'
    }

    environment {
        DOCKER_REGISTRY_URL = 'localhost:5000'
    }

    options {
        timeout(time: 5, unit: 'MINUTES')
    }

    stages {
        stage('Build') {
            options {
                timeout(time: 1, unit: 'MINUTES')
            }

            steps {
                dir('auth') {
                     sh '''
                         mvn clean package
                     '''
                }
            }
        }

        stage('Integration Tests') {
            options {
                timeout(time: 1, unit: 'MINUTES')
            }

            steps {
                dir('auth') {
                    sh '''
                        mvn test
                    '''
                }
            }
        }

        stage('Build Image') {
            options {
                timeout(time: 1, unit: 'MINUTES')
            }

            steps {
                dir('auth') {
                    sh '''
                        docker build -t ${DOCKER_REGISTRY_URL}/rbp-auth:1.0 .
                    '''
                }
            }
        }

        stage('Push Image') {
            options {
                timeout(time: 1, unit: 'MINUTES')
            }

            steps {
                sh '''
                    docker push ${DOCKER_REGISTRY_URL}/rbp-auth:1.0
                '''
            }
        }
    }

    post {
        always  {
            dir('auth') {
                junit 'target/surefire-reports/**/*.xml'
            }
        }
    }
}