version: '3.8'

services:
  rbp-auth:
    image: ${DOCKER_REGISTRY_URL-}/rbp-auth:${RBP_SERVICE_DOCKER_IMAGE_TAG:-latest}
    networks:
      - jenkins
    environment:
      AUTH_DB_JDBC_URL: jdbc:postgresql://postgres:5432/test?loggerLevel=OFF
      AUTH_DB_JDBC_USERNAME: postgres
      AUTH_DB_JDBC_PASSWORD: postgres
    ports:
      - "${RBP_SERVICE_PORT}:3004"
    depends_on:
      postgres:
        condition: service_started
    restart: always
    healthcheck:
      test: curl http://localhost:3004/auth/actuator/health
      interval: 7s
      timeout: 5s
      retries: 3
      start_period: 10s

  postgres:
    image: ${DOCKER_REGISTRY_URL-}/rbp-auth-postgres-test:15.2-alpine
    networks:
      - jenkins
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432"

networks:
  jenkins:
    external: true