pipeline {
    agent {
        label 'build-agent'
    }

    environment {
        DOCKER_REGISTRY_URL = 'localhost:5000'
        RBP_AUTH_SERVICE_MAIN_DIR = 'auth'
        RBP_AUTH_SERVICE_CI_DIR = 'auth/ci'
        RBP_AUTH_SERVICE_PORT = '3004'
        RBP_AUTH_SERVICE_URL = "http://localhost:${RBP_AUTH_SERVICE_PORT}/auth"
    }

    options {
        timeout(time: 7, unit: 'MINUTES')
    }

    stages {
        stage('Build') {
            options {
                timeout(time: 1, unit: 'MINUTES')
            }

            steps {
                dir("${RBP_AUTH_SERVICE_MAIN_DIR}") {
                     sh 'mvn clean package'
                }
            }
        }

        stage('Integration Tests') {
            options {
                timeout(time: 1, unit: 'MINUTES')
            }

            steps {
                dir("${RBP_AUTH_SERVICE_MAIN_DIR}") {
                    sh 'mvn test'
                }
            }
        }

        stage('Build Image') {
            options {
                timeout(time: 1, unit: 'MINUTES')
            }

            steps {
                dir("${RBP_AUTH_SERVICE_MAIN_DIR}") {
                    sh 'docker build -t ${DOCKER_REGISTRY_URL}/rbp-auth:1.0 .'
                }
            }
        }

        stage('Performance Tests') {
            options {
                timeout(time: 1, unit: 'MINUTES')
            }

            steps {
                dir("${RBP_AUTH_SERVICE_CI_DIR}") {
                    sh 'docker compose -f docker-compose-test.yaml up -d --build --wait'
                    bzt 'performance-test.yaml'
                }
            }
        }

        stage('Push Image') {
            options {
                timeout(time: 1, unit: 'MINUTES')
            }

            steps {
                sh 'docker push ${DOCKER_REGISTRY_URL}/rbp-auth:1.0'
            }
        }
    }

    post {
        always  {
            dir("${RBP_AUTH_SERVICE_MAIN_DIR}") {
                junit 'target/surefire-reports/**/*.xml'
                jacoco(
                    execPattern: 'target/**/*.exec',
                    classPattern: 'target/classes/com/rbp',
                    sourcePattern: 'src/main/java/com/rbp'
                )
            }

            dir("${RBP_AUTH_SERVICE_CI_DIR}") {
                sh 'docker compose -f docker-compose-test.yaml down'
            }
        }
    }
}