pipeline {
    agent {
        label 'build-agent'
    }

    environment {
        DOCKER_REGISTRY_URL = 'localhost:5000'
        RBP_AUTH_SERVICE_MAIN_DIR = 'auth'
        RBP_AUTH_SERVICE_CI_DIR = 'auth/ci'
    }

    options {
        timeout(time: 6, unit: 'MINUTES')
    }

    stages {
        stage('Build') {
            options {
                timeout(time: 1, unit: 'MINUTES')
            }

            steps {
                dir("${RBP_AUTH_SERVICE_MAIN_DIR}") {
                     sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Integration Tests') {
            options {
                timeout(time: 1, unit: 'MINUTES')
            }

            steps {
                dir("${RBP_AUTH_SERVICE_MAIN_DIR}") {
                    sh 'mvn surefire:test'
                }
            }
        }

        stage('Build Image') {
            options {
                timeout(time: 30, unit: 'SECONDS')
            }

            steps {
                dir("${RBP_AUTH_SERVICE_MAIN_DIR}") {
                    sh 'docker build -t ${DOCKER_REGISTRY_URL}/rbp-auth:1.0 .'
                }
            }
        }

        stage('Performance Tests') {
            options {
                timeout(time: 1, unit: 'MINUTES')
            }

            environment {
                RBP_AUTH_SERVICE_HOSTNAME = 'rbp-auth'
                RBP_AUTH_SERVICE_PORT = '3004'
            }

            steps {
                dir("${RBP_AUTH_SERVICE_CI_DIR}") {
                    sh 'docker compose -f docker-compose-test.yaml up -d --build --wait'
                    bzt """-o settings.env.JMETER_HOME=${JMETER_HOME} \
                        -o settings.env.RBP_AUTH_SERVICE_HOSTNAME=${RBP_AUTH_SERVICE_HOSTNAME} \
                        -o settings.env.RBP_AUTH_SERVICE_PORT=${RBP_AUTH_SERVICE_PORT} \
                        performance-test.yaml"""
                }
            }
        }

        stage('Push Image') {
            options {
                timeout(time: 30, unit: 'SECONDS')
            }

            steps {
                sh 'docker push ${DOCKER_REGISTRY_URL}/rbp-auth:1.0'
            }
        }
    }

    post {
        always  {
            dir("${RBP_AUTH_SERVICE_MAIN_DIR}") {
                junit 'target/surefire-reports/**/*.xml'
                jacoco(
                    execPattern: 'target/**/*.exec',
                    classPattern: 'target/classes/com/rbp',
                    sourcePattern: 'src/main/java/com/rbp'
                )
            }

            dir("${RBP_AUTH_SERVICE_CI_DIR}") {
                sh '''
                    docker compose -f docker-compose-test.yaml logs && \
                    docker compose -f docker-compose-test.yaml down --volumes
                '''
            }
        }
    }
}